pengutronix/umpf

- umpf
The `--base` and `--name` parameters are documented to overwrite the base and name settings. Don't let umpf init/build/tag ask for base or name again when those parameters are provided.
> Honor --base and --name parameters in umpf init/build/tag

- .github/workflows/ci.yml
- pre-commit
- umpf
Fix shellcheck warnings and run `shellcheck -S warning -e SC2155 umpf` as a GitHub action on every push and pull request. 
Ignore shellcheck warning SC2155 ("Declare and assign separately to avoid masking return values.")
An optional git pre-commit hook can be activated via `ln -s ../../pre-commit .git/hooks/pre-commit`.
> Avoid shellcheck warnings

- tests/meson.build
Explicitly find the run-test shell script once, instead of implicitly each time the file list is passed to test().
> Use find_program() instead of files() for the run-test script

- .github/workflows/ci.yml
- tests/run-test
This allows commits made by tests to have reproducible hashes when tests are run locally instead of via GitHub actions.
> Move git user name and email configuration into test runner

- umpf
Add support for the ternary conditional operator to the Perl regular expression that is used to append the project version in meson.build files.
This is required for Mesa 23.0.0-rc1 and later, to support the following expression:
```
meson.version().version_compare('>= 0.56') ? meson.project_source_root() : meson.source_root()
```
Edit: It looks like this will be required for Mesa 23.0.x but not for later versions.
> Add ternary conditional operator support to Meson project version fixup

- umpf
If `meson.build` is set up to fetch the project version from a `VERSION` file, append the version fixup to that file.
This will be required for Mesa 23.1.0-rc1 and later.
> Add VERSION file support to Meson project version fixup

- umpf
The Makefile for the trusted-firmware-a software is a bit special since it has no EXTAVERSION variable instead they use a VERSION_STRING variable. The variable is composed by:
```
ifeq (${BUILD_STRING},)
BUILD_STRING  :=  $(shell git describe --always --dirty --tags 2> /dev/null)
endif
VERSION_STRING    :=  v${VERSION_MAJOR}.${VERSION_MINOR}(${BUILD_TYPE}):${BUILD_STRING}
```
Append the final VERSION_STRING variable with the umpf version to be independent of the set/not set BUILD_STRING variable.
The output before this patch was (BUILD_STRING not set):
```
NOTICE:  BL31: v2.7(release):v2.7
```
With this patch applied the output will be:
```
NOTICE:  BL31: v2.7(release):v2.7-20221109-2
```
Signed-off-by: Marco Felsch <m.felsch@pengutronix.de>
> Add support for trusted-firmware-a releases

- umpf
This way, "git describe" will produce a nicer result.
Fixes: #12
> Make the umpf tag annotated as well

- umpf
libcamera uses Semantic Versioning, which allows for build metadata:
"Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version." [0]
Adjust the extraversion generation accordingly for libcamera.
[0] https://semver.org/#spec-item-10
Closes #11
> umpf: add support for libcamera

- tests/umpf-distribute
"git checkout" is not available in older git versions.
> tests: use checkout instead of switch

- tests/umpf-distribute
Add the missing --base parameter and make sure that each branch actually received one patch.
> Fix umpf-distribute test

- umpf
If one runs umpf-distribute with no new patches added, the script outputs some benign but ugly errors and prompts for user input when there is nothing to do. Example:
linux $ umpf distribute
umpf: Using series from commit message...
umpf: Remote undefined. Choose the branch with the correct remote:
0) yoyo/v6.1/topic/fixes
1) v6.1/topic/fixes
branch number: 0
umpf: Using remote 'yoyo/'.
/home/alvin/bin/umpf: line 1570: .git/umpf/diff: No such file or directory
/home/alvin/bin/umpf: line 1571: ${patches_in}: ambiguous redirect
/home/alvin/bin/umpf: line 1576: patches_in: ambiguous redirect
umpf: Updating remote topic branches for 'yoyo/'...
Press Enter to continue.
linux $
To improve the user experience, check if there is no diff, and in that case print a friendly info message instead. …
> umpf: suppress umpf-distribute errors when there is no diff

- umpf
When umpf compares branches between all of the known remotes, it warns when a discovered branch includes additional commits compared to the one on the selected remote. The user is warned, but has no choice to use the alternative remote and include the commits.
This commit adds a choice to the user in the situation described above. This is useful to facilitate generating an umpf-tag with some local changes when working on projects with multiple developers pushing to the same common branches, i.e. where the remote is not to be updated until the changes are verified and ready to merge.
> umpf: add branch choice in case of additional commits

- umpf
When umpf compares branches between all of the known remotes, it will now prompt the user when it discovers a branch that includes additional commits compared to the one on the selected remote.
If the user confirms, the branch name is taken as is, which would result in an umpf-hashinfo of e.g. heads/v6.4/topic/something, which breaks the ability of doing identical umpfs.
To restore that ability, we need to call rev-parse on the ${branch}.
Fixes: 000e642bc702 ("umpf: add branch choice in case of additional commits")
> umpf: call rev-parse on manually selected local branches as well

- doc/tips.rst
- umpf
In one project, umpf tags are pushed immediately, but branches are only pushed upstream once they are reviewed and cleared for merge into BSP. It's thus often the case, that developers want to use the upstream branches, except for that one branch they are currently working on.
This is not an unusual case and the tips-and-tricks lists some workarounds to achieve this. Provide a better way by allowing overriding single topic branches on the command-line.
> umpf: add new --override option to override topic commit-ish

- README.rst
The automatic checks for pull requests on Github include a check that fails if a Signed-off-by: line by the commiter is missing in any commit.
For that to make sense formalize the meaning of such a line. I'm not a lawyer (thank heavens!) but I believe that without such a formalisation you cannot safely assume the "usual semantic also used in other open-source projects".
> README: Formalize signing off commits

- umpf
git commit --fixup=amend:$rev allows to overwrite the commit message of a previous commit. This results in a commit with prefix "amend!". Expand the pattern that triggers using git rebase -i --autosquash to also match on such commits.
> Properly squash commits created by git commit --fixup=amend:$rev

- umpf
Add support to specify umpf-flags which influence the umpf build behaviour. The flags are tracked within the umpf tag via the new 'umpf-flags' section. Users can flags directly via the useries or by specfiy them via the command line option '--flags'.
The EXTRAVERSION patch conflicts if a stable update is done without using umpf, e.g. if multiple parties do stable updates for certain software package like Linux but only a few of them use umpf.
To avoid EXTRAVERSION conflicting each time a stable update is done we shift the EXTRAVERSION patching down into the middle of the Makefile by using the new umpf-flags mechanism:
New flags can be added by extending the SUPPORTED_FLAGS list and adding the flag_<flag> array, e.g.:
SUPPORTED_FLAGS=("extraversion" "foo")
...
flag_foo[val] = "baz"		# …
> Add umpf-flags support to control the EXTRAVERSION patching

- umpf
The flags implementation loses the flags if they are provided via umpf build followed by an umpf tag, e.g:
- umpf build <useries containing flags> && umpf tag
- umpf build <useries> --flags <flags> && umpf tag
In this case the flags are lost. Fix this by storing the flags and adding a build note like it is done for base and name.
> umpf: fix ignoring flags

- umpf
Two smaller enhancements. The first commit makes umpf easier to use on distributions not shipping `/bin/bash`, the second makes `umpf show` to capture a series with multiple branches more convenient.
> Smaller fixes

- umpf
Add support to create nix.series files which can than be imported into a nix kernel build as a patch series.
> umpf: add support for nix files

- tests/series-format-patch-bb.ref
- umpf
This sets PV to the exact umpf version.
This is especially useful when using the series.inc together with the linux-yocto.bbclass version checking which expects PV to match the full kernel version.
> umpf: output version infos to bitbake variables during format-patch

- tests/series-format-patch-bb.ref
- umpf
Since most recipes tend to use PV in their `SRC_URI` and we cannot set it as a default value (`?=`), it is the safest way to not set it automatically from series.inc.
Users who want to have UMPF_VERSION as part of the yocto package version can manually set PV to
PV = "${UMPF_BASE}-${UMPF_VERSION}
at an appropriate location within the recipe.
> umpf: do not set PV in series.inc

- umpf
There are cases where topic branches do have empty commits e.g. if the topic branches are managed via b4 [1]. b4 uses empty commits to track metadata. This is useful for topic branch management but shouldn't be part of the final umpf-tag. Therefore add --no-keep-empty to skip empty commits during the rebase.
[1] https://github.com/mricon/b4
> Skip empty commits for umpf-tags

- umpf
Add the `-l|--local` option as an alias for `--remote refs/heads`, which causes umpf to use local branches.
> umpf: add -l|--local option as a shortcut to use local branches

- bash_completion
- umpf
The 'tig' subcommand makes it possible to browse an umpf interactively while showing the local and remote state of all topic branches. This can give an overview how the topic branches have developed before building another umpf.
For simplicity sake, also limit the range of the topics to the history leading up from the umpf-base.
> tig: add subcommand to browse an umpf and its context interactively

- umpf
> umpf: fix indentation of --nix in usage

- umpf
Prior to processing the overrides, `GIT_REMOTE`, if set, is appended with a slash. Adding an extra slash later thus introduces breakage when no remote is specified:
```
Revision '/v6.9/topic/foo' not found for topic 'v6.9/topic/foo'
```
Fix by dropping the unnecessary slash.
> umpf: fix extra / when using --override=singlearg

- umpf
For fixup commits, we can expect that the commit is supposed to be squashed into the referenced commit. So find the branch that contains this commit and provide it as default during "distribute".
> umpf: distribute: provide default branch for fixup commits if possible

- umpf
Some of these commands can take a useries too, which is not a commit-ish. Also some commands can work on the currently checked-out umerge or utag, so in this case an argument is optional.
> improve command syntax in help text

- umpf
When building or tagging an umpf, umpf can ask which branch to use when multiple are available. Piping `yes(1)` into umpf in this case doesn't work, because the variable populated by read in that case is left empty.
Handle this case to reduce user confusion.
> umpf: answer interactive prompts with default when --default set 

- umpf
Umpf already supports stable updates outside of umpf if the extraversion=conflictfree was provided for the umpf-tag.
This patch allow the Yocto users to override LINUX_VERSION from anywhere within a recipe which can be the case if the initial umpf-tag was provided by another team than the one doing the maintenance work (stable updates).
> umpf: make LINUX_VERSION a weak assignment

- tests/series-format-patch-bb.ref
- umpf
This will put all umpf-relates SRC_URI adaptions into the variable UMPF_SRC_URI, which potentially allows separating them from other SRC_URI entries (and patches).
With this, one can simply deactivate the umpf patches by setting
UMPF_SRC_URI = ""
> umpf: write umpf patches into separate bitbake variable
